package com.stee.spfcore.model.sag;

public enum SAGDateConfigType {

	APP_OPENING,
	APP_CUT_OFF,
	PRIVILEGED_CUT_OFF,
	APP_PROCESSING_CUT_OFF,
	APP_RESULTS_NOTIFICATION_CUT_OFF,
	RSVP_CUT_OFF,
	RSVP_PROCESSING_CUT_OFF,
	REROUTED_APP_RESPONSE_TIME_IN_DAYS,
	HAS_RSVP,
	PCI_VALUE,
	SG_PERCENTILE_VALUE,
	PAYMENT_MODE
	
}
